"""Render the MetricSpec registry as a markdown catalog.

Emits a single file at ``docs/metrics/catalog.md`` (repo root) containing:
  - one row per registered MetricSpec (key, category, activity flag, paired
    outcome, visibility, distribution flag, goodhart risk, notes, description)
  - one row per BANNED metric (name, reason)

Re-run this after editing ``backend/app/services/metric_spec.py`` so the
committed catalog stays in sync with the registry. A pytest in
``tests/unit/test_metrics_catalog.py`` asserts they match so drift breaks CI.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Allow ``python backend/scripts/generate_metrics_catalog.py`` to import app.*.
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))

from app.services.metric_spec import BANNED_METRICS, REGISTRY  # noqa: E402


HEADER = """# Metrics catalog

> Generated by `backend/scripts/generate_metrics_catalog.py` — re-run after
> registry changes. Do not edit by hand.

Every metric surfaced to the UI registers a `MetricSpec` in
`backend/app/services/metric_spec.py`. The fields below drive:

- Tooltip and paired-outcome wiring on stat cards
- Visibility defaults (`self` / `team` / `admin`)
- Distribution-style rendering for metrics requiring p50 + p90 (histogram)
- Goodhart risk disclosure so readers know what each number distorts when
  optimized for in isolation

Activity metrics (`is_activity=True`) must declare a `paired_outcome_key`;
this is enforced at import time by `MetricSpec.__post_init__`.

## Registered metrics

"""


def _escape(value: str | None) -> str:
    """Markdown-safe cell content: collapse newlines, escape pipes."""
    if value is None:
        return ""
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render() -> str:
    lines: list[str] = [HEADER]
    lines.append(
        "| key | label | category | activity | paired_outcome | visibility | "
        "distribution | goodhart_risk | goodhart_notes | description |"
    )
    lines.append(
        "|-----|-------|----------|----------|----------------|------------|"
        "--------------|---------------|----------------|-------------|"
    )
    for spec in REGISTRY:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_escape(spec.key)}`",
                    _escape(spec.label),
                    _escape(spec.category),
                    "yes" if spec.is_activity else "no",
                    f"`{_escape(spec.paired_outcome_key)}`"
                    if spec.paired_outcome_key
                    else "—",
                    _escape(spec.visibility_default),
                    "yes" if spec.is_distribution else "no",
                    _escape(spec.goodhart_risk),
                    _escape(spec.goodhart_notes),
                    _escape(spec.description),
                ]
            )
            + " |"
        )

    lines.append("")
    lines.append("## Banned metrics")
    lines.append("")
    lines.append(
        "Metrics DevPulse explicitly does not expose. Recorded here so the "
        "decision is visible and reversible."
    )
    lines.append("")
    lines.append("| key | reason |")
    lines.append("|-----|--------|")
    for row in BANNED_METRICS:
        lines.append(f"| `{_escape(row['key'])}` | {_escape(row['reason'])} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    target = ROOT / "docs" / "metrics" / "catalog.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    output = render()
    target.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {target.relative_to(ROOT)} ({len(output)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
